[package]
authors = ["Wez Furlong <wez@wezfurlong.org>"]
name = "varbincode"
version = "0.1.0"
edition = "2018"

[dependencies]
byteorder = "1.3"
leb128 = "0.2"
serde = "1.0"

[dev-dependencies]
serde_derive = "~1.0"
