[package]
name = "time-funcs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
chrono = {version="0.4", default-features=false, features=["unstable-locales"]}
config = { path = "../../config" }
luahelper = { path = "../../luahelper" }
lazy_static = "1.4"
promise = { path = "../../promise" }
smol = "1.2"
spa = {version="0.3", git="https://github.com/wez/spa-rs.git", rev="b7b5bc5e1cec209dd1595a2592b89171e46ef378"}
wezterm-dynamic = { path = "../../wezterm-dynamic" }
