[package]
name = "time-funcs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
chrono = {version="0.4", features=["unstable-locales"]}
config = { path = "../../config" }
luahelper = { path = "../../luahelper" }
spa = "0.3"
wezterm-dynamic = { path = "../../wezterm-dynamic" }
