freebsd_instance:
  image: freebsd-12-1-release-amd64
  cpu: 4
  memory: 8G

task:
  name: freebsd-12
  stateful: false
  setup_script:
    - pkg install -y bash
    - bash get-deps
    - curl https://sh.rustup.rs -sSf > /tmp/rustup.sh
    - chmod +x /tmp/rustup.sh
    - /tmp/rustup.sh -y -q
  test_script:
    - env PATH=$HOME/.cargo/bin:$PATH cargo build --all --release
    - env PATH=$HOME/.cargo/bin:$PATH cargo test --all --release
