language: rust
sudo: required

cache: cargo

rust:
  - stable
  - beta

os:
  - osx
  - linux
  - windows

dist: xenial

matrix:
  allow_failures:
    - rust: beta
    - os: windows

before_script:
  - rustup component add rustfmt-preview

script:
  - bash ./ci/travis-run.sh

addons:
  apt:
    packages:
      - binutils-dev
      - cmake
      - gcc
      - xorg-dev
      - libcurl4-openssl-dev
      - libdw-dev
      - libegl1-mesa-dev
      - libelf-dev
      - libfontconfig1-dev
      - libiberty-dev
      - libxcb-ewmh-dev
      - libxcb-icccm4-dev
      - libxcb-keysyms1-dev
      - libxcb-xkb-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-dev
      - ragel

before_deploy:
  - bash ci/deploy.sh

deploy:
  provider: releases
  api_key:
    secure: IfuwRuR0rXgdxnBcjFzOgKwxWMs/xpB5J1WpSdgBJjbA6AGdB2K5FUqWAEm6XxWD/M9QRAT4JrYgQR/+bKXOhXDAL8bOCsG9RAQirfGZ0Ne7TvrJKHqmx3CrCPo5OB49Fh12Q8f6wjOnwT8MMmdVHIreKVlj9A+EjJYgyNZKhrXDZH/IB8zXKAeVI6bUs0e3bIpfKGDYzIkEJV37115Hi7FnU781q8EQYnadMq4YYQRQpuTspD7GQ/Thur+x/+mExmQ+LG1vBY07Fu/H+p7ikrLMVmIuaUKRC/X09xGKABP3lKVw8lzpQtwlSWRVt1qQYDqNR1dklPD6LcR8jrDDtN+bOCgD6SXQc1kU9iQJizng0a3fibbJmAj2Om9kTRW73OfMbDgX1jDKhA9Swt/CJ6nbHqrRVdczhkdIzFdV3ceNkCSBMrlDnOsvrZWVp9foQFjTa0Ij6q5C1yLW8D8hkoY6lJJeGuzFqBPcPBhHe463/Fgs77xAVrfA8JLOEZbt6yMwGv0dNcsJihr39zVyNlRLeaLEl2wDTDfL2L4j98YM8hR7vo81awls1ZGwWBKqTw4dt2XQmsfY6Rn0WZJBqdiEPOS+C31Bqcq2dFfbJyKswrQQsoNxxl2KiKNo4VWS9xNmRvaQlNdKfxk2osM4nbf+YpNK4DKuqX15DdgVtrE=
  file_glob: true
  file: WezTerm*.zip
  skip_cleanup: true
  on:
    repo: wez/wezterm
    tags: true
    rust: stable
    condition: $TRAVIS_OS_NAME = osx

