language: rust
sudo: required

cache: cargo

rust:
  - stable
  - beta
  - nightly

os:
  - osx
  - linux
  - windows

dist: xenial

matrix:
  allow_failures:
    - rust: beta
    - rust: nightly
    - os: windows

before_script:
  - rustup component add rustfmt-preview

script:
  - "if [[ \"$TRAVIS_RUST_VERSION\" == \"stable\" ]] ; then cargo fmt --all -- --check ; else true ; fi"
  - cargo build --verbose
  - cargo test --verbose -p term -p termwiz -p wezterm -p base91 -p varbincode

addons:
  apt:
    packages:
      - binutils-dev
      - cmake
      - gcc
      - xorg-dev
      - libcurl4-openssl-dev
      - libdw-dev
      - libegl1-mesa-dev
      - libelf-dev
      - libfontconfig1-dev
      - libiberty-dev
      - libxcb-ewmh-dev
      - libxcb-icccm4-dev
      - libxcb-keysyms1-dev
      - libxcb-xkb-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-dev
      - ragel
