# Note that travis has been disabled because the Trusty harfbuzz
# library doesn't have `hb_ft_font_create_referenced` and we require it
language: rust
rust:
  #  - stable  we use a feature flag that precludes this
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxcb-icccm4-dev libxcb-ewmh-dev libxcb-image0-dev libxcb-keysyms1-dev libharfbuzz-dev libfontconfig1-dev libfreetype6-dev
