# vim:et:sw=2:ts=2:

schedules:
  - cron: '50 * * * *'
    displayName: "scheduled GH Pages re-deploy"
    branches:
      include: ['master']

jobs:
  - job: 'Rebuild_GH_Pages'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - bash: 'curl -u wez:$(github.pat) -X POST https://api.github.com/repos/wez/wezterm/pages/builds -H "Accept: application/vnd.github.mister-fantastic-preview+json"'
        displayName: request github pages rebuild

