[package]
name = "termwiz"
version = "0.1.0"
authors = ["Wez Furlong"]

[dependencies]
# SetAttributes is only in master
terminfo = { git = "https://github.com/meh/rust-terminfo" }
palette = "~0.4"
serde = "~1.0"
serde_derive = "~1.0"
failure = "~0.1"
vte = "0.3.2"
num = "0.2.0"
num-derive = "0.2.2"
num-traits = "0.2.5"
