[package]
authors = ["Wez Furlong <wez@wezfurlong.org>"]
name = "wterm"
version = "0.1.0"

[dependencies]
bitflags = "1.0.1"
failure = "0.1.1"
freetype = "0.3.0"
harfbuzz-sys = "0.1.15"
libc = "0.2.36"
mio = "0.6.12"
resize = "0.3.0"
servo-fontconfig = "0.4.0"
unicode-segmentation = "1.2.0"
unicode-width = "0.1.4"
vte = "0.3.2"
xcb = "0.8.1"

[dependencies.xcb-util]
features = [
    "image",
    "icccm",
    "ewmh",
    "misc",
    "shm",
    "keysyms",
]
version = "0.2.0"
