[package]
authors = ["Wez Furlong <wez@wezfurlong.org>"]
name = "wezterm"
version = "0.1.0"

[dependencies]
bitflags = "1.0.1"
egli = "0.4.0"
euclid = "0.17.0"
failure = "0.1.1"
gl = "0.10.0"
libc = "0.2.36"
mio = "0.6.12"
palette = "0.2.1"
serde = "1.0.27"
serde_derive = "1.0.27"
servo-fontconfig = "0.4.0"
toml = "0.4.5"
unicode-width = "0.1.4"

[dependencies.glium]
default-features = false
version = "0.20.0"

[dependencies.harfbuzz]
path = "harfbuzz"

[dependencies.term]
path = "term"

[target.'cfg(any(target_os = "android", all(unix, not(target_os = "macos"))))'.dependencies]
freetype = "0.3"

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies.x11]
features = ["xlib"]
version = "2.17.2"

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies.xcb]
version = "0.8.1"

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies.xcb-util]
features = [
    "icccm",
    "ewmh",
    "keysyms",
]
version = "0.2.0"

[features]
debug-escape-sequences = ["term/debug-escape-sequences"]

[workspace]
