[package]
authors = ["Wez Furlong <wez@wezfurlong.org>"]
name = "wezterm"
version = "0.1.0"

[dependencies]
bitflags = "1.0.1"
clap = "2.30.0"
euclid = "0.17.0"
failure = "0.1.1"
failure_derive = "0.1.1"
gl = "0.10.0"
glium = "0.20.0"
harfbuzz-sys = "0.1.15"
libc = "0.2.36"
mio = "0.6.12"
palette = "0.2.1"
serde = "1.0.27"
serde_derive = "1.0.27"
toml = "0.4.5"
unicode-width = "0.1.4"

[dependencies.term]
path = "term"

[target.'cfg(any(target_os = "android", all(unix, not(target_os = "macos"))))'.dependencies]
freetype = "0.3"
servo-fontconfig = "0.4.0"

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies.xcb]
version = "0.8.1"

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies.xcb-util]
features = [
    "icccm",
    "ewmh",
    "keysyms",
]
version = "0.2.0"

[target.'cfg(target_os = "macos")'.dependencies]
core-text = "9.2.0"

[features]
debug-escape-sequences = ["term/debug-escape-sequences"]

[workspace]
