[package]
name = "termwiz"
version = "0.1.0"
authors = ["Wez Furlong"]

[dependencies]
# SetAttributes is only in master
terminfo = { git = "https://github.com/meh/rust-terminfo" }
palette = "~0.4"
serde = "~1.0"
serde_derive = "~1.0"
failure = "~0.1"
