[package]
authors = ["Wez Furlong <wez@wezfurlong.org>"]
name = "wezterm"
version = "0.1.0"

[dependencies]
bitflags = "~1.0"
clap = "~2.30"
euclid = "~0.17"
failure = "~0.1"
failure_derive = "~0.1"
futures = "~0.1"
gl = "~0.10"
harfbuzz-sys = "~0.1"
libc = "~0.2"
mio = "~0.6"
mio-extras = "~2.0"
palette = "~0.2"
serde = "~1.0"
serde_derive = "~1.0"
toml = "~0.4"
unicode-width = "~0.1"
directories = "~1.0"

[dependencies.term]
path = "term"

[target.'cfg(any(target_os = "android", all(unix, not(target_os = "macos"))))'.dependencies]
freetype = "0.3"
servo-fontconfig = "~0.4"
egli = "~0.4"
x11 = {version ="~2.17", features = ["xlib_xcb"]}

[target.'cfg(any(target_os = "android", all(unix, not(target_os = "macos"))))'.dependencies.glium]
version = "~0.20"
default-features = false
features = []

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies.xcb]
version = "~0.8"

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies.xcb-util]
features = [
    "icccm",
    "ewmh",
    "keysyms",
]
version = "~0.2"

[target.'cfg(target_os = "macos")'.dependencies]
core-text = "~9.2"

[features]
debug-escape-sequences = ["term/debug-escape-sequences"]

[workspace]
