[workspace]
members = [
  "strip-ansi-escapes",
  "wezterm",
  "wezterm-gui",
  "wezterm-mux-server",
  "wezterm-ssh"
]
resolver = "2"

[profile.release]
opt-level = 3
# debug = 1

[patch.crates-io]
ssh2 = { git = "https://github.com/wez/ssh2-rs.git", branch="win32ssl" }
