[package]
name = "termwiz"
version = "0.1.0"
authors = ["Wez Furlong"]

[dependencies]
# SetAttributes is only in master
terminfo = { git = "https://github.com/meh/rust-terminfo" }
palette = "~0.4"
serde = "~1.0"
serde_derive = "~1.0"
failure = "~0.1"
vte = "0.3.2"
num = "0.2.0"
num-traits = "0.2.5"
derive_builder = "0.5.1"
semver = "0.9.0"
libc = "0.2.42"

[target.'cfg(windows)'.dependencies]
winapi = {version = "~0.3", features = ["winuser", "consoleapi", "handleapi", "fileapi"]}

[target.'cfg(unix)'.dependencies]
termios = "0.3.0"

[dependencies.num-derive]
version = "~0.2"
features = ["full-syntax"]
