[package]
authors = ["Wez Furlong <wez@wezfurlong.org>"]
name = "wterm"
version = "0.1.0"

[dependencies]
failure = "0.1.1"
hexdump = "0.1.0"
unicode-width = "0.1.4"
vte = "0.3.2"

[dependencies.font]
path = "font"

[dependencies.sdl2]
features = [
    "bundled",
    "static-link",
]
version = "0.31.0"
