[package]
name = "wezterm-ssh"
version = "0.1.0"
authors = ["Wez Furlong <wez@wezfurlong.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
base64 = "0.13"
dirs-next = "2.0"
filedescriptor = { version="0.7", path = "../filedescriptor" }
log = "0.4"
portable-pty = { path = "../pty" }
regex = "1"
smol = "1.2"
ssh2 = "0.9"

[dev-dependencies]
k9 = "0.11.0"
pretty_env_logger = "0.4"
shell-words = "1.0"
structopt = "0.3"
termwiz = { path = "../termwiz" }
