[package]
name = "sync-color-schemes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
config = { path = "../config" }
reqwest = "0.11"
lazy_static = "1.4"
tokio = { version = "1.19", features = ["rt-multi-thread", "sync", "macros"] }
serde = {version="1.0", features=["derive"]}
rusqlite = {version="0.27", features=["bundled", "blob"]}
serde_json = "1.0"
sqlite-cache = "0.1.3"
toml = "0.5"
wezterm-dynamic = { path = "../wezterm-dynamic" }
yaml-rust = "0.4.5"
