[package]
authors = ["Wez Furlong <wez@wezfurlong.org>"]
name = "term"
version = "0.1.0"

[dependencies]
bitflags = "1.0.1"
failure = "0.1.1"
maplit = "1.0.1"
regex = "0.2.6"
serde = "1.0.27"
serde_derive = "1.0.27"
unicode-segmentation = "~1.2"
unicode-width = "~0.1"

[dependencies.termwiz]
path = "../../termwiz"

[features]
debug-escape-sequences = []
