[package]
authors = ["Wez Furlong <wez@wezfurlong.org>"]
name = "wezterm-term"
version = "0.1.0"
edition = "2018"
repository = "https://github.com/wez/wezterm"
description = "The Virtual Terminal Emulator core from wezterm; helpful for implementing terminal emulators"
license = "MIT"
documentation = "https://docs.rs/wezterm-term"
keywords = ["terminal", "emulator", "vte"]
readme = "README.md"

[features]
use_serde = ["termwiz/use_serde"]

[dependencies]
bitflags = "1.0"
anyhow = "1.0"
image = "0.23"
log = "0.4"
num-traits = "0.2"
ordered-float = "1.0"
palette = "0.5"
unicode-segmentation = "1.6"
unicode-width = "0.1"
serde = {version="1.0", features = ["rc"]}
url = "2"

[dev-dependencies]
pretty_assertions = "0.6"

[dependencies.termwiz]
version = "0.10"
path = "../termwiz"
