[package]
name = "wezterm-toast-notification"
version = "0.1.0"
authors = ["Wez Furlong <wez@wezfurlong.org>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
open = "1.4"

[target.'cfg(all(not(windows), not(target_os="macos")))'.dependencies]
# show a notification
notify-rust = "4"

[target.'cfg(target_os="macos")'.dependencies]
cocoa = "0.20"
core-foundation = "0.7"
objc = "0.2"

[target.'cfg(windows)'.dependencies]
winrt-notification = "0.2"
