[package]
name = "wezterm-bidi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
use_serde = ["serde"]

[dependencies]
log = "0.4"
serde = {version="1.0", features = ["derive"], optional=true}

[dev-dependencies]
k9 = "0.11.0"
pretty_env_logger = "0.4"
