[package]
name = "window"
version = "0.1.0"
authors = ["Wez Furlong"]
edition = "2018"
repository = "https://github.com/wez/wezterm"
description = "Cross platform window setup and render"
license = "MIT"

[dependencies]
failure = "0.1"
failure_derive = "0.1"
promise = { path = "../promise" }

[features]

[target."cfg(windows)".dependencies]
lazy_static = "1.3"
shared_library = "0.1"
uds_windows = "0.1"
winapi = { version = "0.3", features = [
    "dwmapi",
    "winuser",
    "consoleapi",
    "handleapi",
    "fileapi",
    "namedpipeapi",
    "synchapi",
]}

