[package]
name = "window"
version = "0.1.0"
authors = ["Wez Furlong"]
edition = "2018"
repository = "https://github.com/wez/wezterm"
description = "Cross platform window setup and render"
license = "MIT"

[dependencies]
failure = "0.1"
failure_derive = "0.1"
promise = { path = "../promise" }

[features]

[target."cfg(windows)".dependencies]
winapi = { version = "0.3", features = [
    "dwmapi",
    "handleapi",
    "libloaderapi",
    "synchapi",
    "winerror",
    "winuser",
]}

