[package]
name = "window"
version = "0.1.0"
authors = ["Wez Furlong"]
edition = "2018"
repository = "https://github.com/wez/wezterm"
description = "Cross platform window setup and render"
license = "MIT"
build = "build.rs"

[dev-dependencies]
pretty_env_logger = "0.4"

[build-dependencies]
gl_generator = {version="0.14", optional=true}

[dependencies]
async-task = "1.2"
anyhow = "1.0"
thiserror = "1.0"
bitflags = "1.0"
euclid = "0.20"
guillotiere = "0.6"
lazy_static = "1.3"
libloading = { version = "0.6", optional=true }
line_drawing = "0.8"
log = "0.4"
metrics = { version="0.12", features=["std"]}
palette = "0.5"
promise = { path = "../promise" }
resize = "0.3"
glium = { version = "0.28", optional=true, default-features = false}

[features]
opengl = ["cgl", "glium", "gl_generator", "libloading"]
wayland = ["smithay-client-toolkit", "memmap", "wayland-client", "wayland-egl"]

[target."cfg(windows)".dependencies]
lazy_static = "1.4"
winapi = { version = "0.3", features = [
    "dwmapi",
    "handleapi",
    "imm",
    "libloaderapi",
    "synchapi",
    "winerror",
    "winuser",
]}
winreg = "0.6"
clipboard-win = "2.2"
shared_library = "0.1"

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies]
filedescriptor = { version="0.7", path = "../filedescriptor" }
x11 = {version ="2.18", features = ["xlib_xcb"]}
xcb = {version="0.9", features=["shm", "xkb", "xlib_xcb"]}
xcb-util = { features = [ "icccm", "ewmh", "keysyms", "shm"], version = "0.3" }
xkbcommon = { version = "0.5", features = ["x11", "wayland"], git="https://github.com/wez/xkbcommon-rs.git", rev="01a0a0cd5663405e6e4abb1ad3add9add1496f58"}
mio = "0.6"
mio-extras = "2.0"
libc = "0.2"
smithay-client-toolkit = {version = "0.9", optional = true, features=["calloop"], git="https://github.com/wez/client-toolkit.git", branch="title_trunc"}
memmap = {version="0.7", optional=true}
wayland-client = {version="0.26", optional=true}
wayland-egl = {version="0.26", optional=true}

[target.'cfg(target_os="macos")'.dependencies]
cocoa = "0.20"
objc = "0.2"
clipboard = "0.5"
core-foundation = "0.7"
core-graphics = "0.19"
cgl = { version = "0.3", optional = true }
