[package]
name = "window"
version = "0.1.0"
authors = ["Wez Furlong"]
edition = "2018"
repository = "https://github.com/wez/wezterm"
description = "Cross platform window setup and render"
license = "MIT"
build = "build.rs"

[build-dependencies]
gl_generator = {version="0.13", optional=true}

[dependencies]
bitflags = "1.0"
euclid = "0.20"
failure = "0.1"
failure_derive = "0.1"
lazy_static = "1.3"
libloading = { version = "0.5", optional=true }
line_drawing = "0.8"
log = "0.4"
palette = "0.4"
promise = { path = "../promise" }
resize = "0.3"
glium = { version = "0.26.0-alpha3", optional=true, default-features = false}

[features]
async_await = []
opengl = ["cgl", "glium", "gl_generator", "libloading"]
wayland = ["smithay-client-toolkit", "memmap"]

[target."cfg(windows)".dependencies]
winapi = { version = "0.3", features = [
    "dwmapi",
    "handleapi",
    "imm",
    "libloaderapi",
    "synchapi",
    "winerror",
    "winuser",
]}
clipboard-win = "2.2"

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies]
filedescriptor = "0.5"
x11 = {version ="2.18", features = ["xlib_xcb"]}
xcb = "0.8"
xcb-util = { features = [ "icccm", "ewmh", "keysyms", "shm"], version = "0.2" }
xkbcommon = { version = "0.4", features = ["x11"] }
mio = "0.6"
mio-extras = "2.0"
libc = "0.2"
smithay-client-toolkit = {version = "0.6", optional = true}
memmap = {version="0.7", optional=true}

[target.'cfg(target_os="macos")'.dependencies]
cocoa = "0.20"
objc = "0.2"
core-foundation = "0.7"
core-graphics = "0.19"
cgl = { version = "0.3", optional = true }
