[package]
name = "portable-pty"
version = "0.1.0"
authors = ["Wez Furlong"]
edition = "2018"
repository = "https://github.com/wez/wezterm"
description = "Cross platform pty interface"
license = "MIT"
documentation = "https://docs.rs/portable-pty"

[dependencies]
failure = "0.1"
failure_derive = "0.1"
filedescriptor = "0.1"
libc = "0.2"
serde_derive = {version="1.0", optional=true}
serde = {version="1.0", optional=true}

[features]
default = []
serde_support = ["serde", "serde_derive"]

[target."cfg(windows)".dependencies]
bitflags = "1.0"
lazy_static = "1.3"
shared_library = "0.1"
uds_windows = "0.1"
winapi = { version = "0.3", features = [
    "winuser",
    "consoleapi",
    "handleapi",
    "fileapi",
    "namedpipeapi",
    "synchapi",
]}

