[package]
name = "portable-pty"
version = "0.1.0"
authors = ["Wez Furlong"]
edition = "2018"
repository = "https://github.com/wez/wezterm"
description = "Cross platform pty interface"
license = "MIT"
documentation = "https://docs.rs/portable-pty"

[dependencies]
failure = "0.1"
failure_derive = "0.1"
filedescriptor = "0.5"
log = "0.4"
libc = "0.2"
shell-words = "0.1"
serde_derive = {version="1.0", optional=true}
serde = {version="1.0", optional=true}
ssh2 = {optional=true, git="https://github.com/wez/ssh2-rs"}
#ssh2 = {optional=true, path="../../ssh2-rs"}

[features]
default = []
serde_support = ["serde", "serde_derive"]
ssh = ["ssh2"]

[target."cfg(windows)".dependencies]
bitflags = "1.0"
lazy_static = "1.3"
shared_library = "0.1"
uds_windows = "0.1"
winapi = { version = "0.3", features = [
    "winuser",
    "consoleapi",
    "handleapi",
    "fileapi",
    "namedpipeapi",
    "synchapi",
]}

