[package]
authors = ["Wez Furlong <wez@wezfurlong.org>"]
name = "harfbuzz"
version = "0.1.0"
edition = "2018"
links = "harfbuzz"
build = "build.rs"

[dependencies]
freetype = { path = "../freetype" }

[build-dependencies]
cmake = "0.1"
