[package]
authors = ["Wez Furlong <wez@wezfurlong.org>"]
name = "harfbuzz"
version = "0.1.0"

[dependencies]
failure = "0.1.1"

[build-dependencies]
cmake = "0.1.29"

[target.'cfg(any(target_os = "android", all(unix, not(target_os = "macos"))))'.dependencies]
freetype = "0.3"
