
name: ubuntu16_tag

on:
  push:
    tags:
      - "20*"


jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: "ubuntu-16.04"
    
    steps:
    - name: "Update APT"
      shell: bash
      run: "sudo -n apt update"
    - name: "Install git"
      shell: bash
      run: "sudo -n apt-get install -y git"
    - name: "checkout repo"
      uses: actions/checkout@v2
      with:
         submodules: "recursive"
    - name: "Fetch tags"
      shell: bash
      run: "git fetch --depth=1 origin +refs/tags/*:refs/tags/*"
    - name: "Fetch tag/branch history"
      shell: bash
      run: "git fetch --prune --unshallow"
    - name: "Install Rust"
      uses: actions-rs/toolchain@v1
      with:
         profile: "minimal"
         toolchain: "stable"
         override: true
         components: "rustfmt"
    - name: "Cache cargo registry"
      uses: actions/cache@v2
      with:
         path: "~/.cargo/registry"
         key: "ubuntu16-None-${{ hashFiles('Cargo.lock') }}-cargo-registry"
    - name: "Cache cargo index"
      uses: actions/cache@v2
      with:
         path: "~/.cargo/git"
         key: "ubuntu16-None-${{ hashFiles('Cargo.lock') }}-cargo-index"
    - name: "Cache cargo build"
      uses: actions/cache@v2
      with:
         path: "target"
         key: "ubuntu16-None-${{ hashFiles('Cargo.lock') }}-cargo-build-target"
    - name: "Install System Deps"
      shell: bash
      run: "sudo -n ./get-deps"
    - name: "Build (Release mode)"
      shell: bash
      run: "cargo build --all --release"
    - name: "Test (Release mode)"
      shell: bash
      run: "cargo test --all --release"
    - name: "Package"
      shell: bash
      run: "bash ci/deploy.sh"
    - name: "Build AppImage"
      shell: bash
      run: "bash ci/appimage.sh"
    - name: "Upload to Tagged Release"
      uses: softprops/action-gh-release@v1
      with:
         files: |
            wezterm-*.deb
            wezterm-*.xz
            wezterm-*.tar.gz
            *.AppImage
            *.zsync

      env:
         GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - name: "Update AUR"
      uses: KSXGitHub/github-actions-deploy-aur@master
      with:
         pkgname: "wezterm-bin"
         pkgbuild: "PKGBUILD"
         commit_username: "wez"
         commit_email: "wez@wezfurlong.org"
         ssh_private_key: "${{ secrets.AUR_SSH_PRIVATE_KEY }}"
         commit_message: "Automated update to match latest tag"
    - name: "Checkout linuxbrew tap"
      uses: actions/checkout@v2
      with:
         repository: "wez/homebrew-wezterm-linuxbrew"
         path: "linuxbrew-wezterm"
         token: "${{ secrets.GH_PAT }}"
    - name: "Update linuxbrew tap formula"
      shell: bash
      run: "cp wezterm-linuxbrew.rb linuxbrew-wezterm/Formula/wezterm.rb"
    - name: "Commit linuxbrew tap changes"
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
         commit_message: "Automated update to match latest tag"
         repository: "linuxbrew-wezterm"
