
name: macos_tag

on:
  push:
    tags:
      - "20*"


jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: "macos-latest"
    
    steps:
    - name: "checkout repo"
      uses: actions/checkout@v2
      with:
         submodules: "recursive"
    - name: "Fetch tags"
      shell: bash
      run: |
            export MACOSX_DEPLOYMENT_TARGET=10.9
            git fetch --depth=1 origin +refs/tags/*:refs/tags/*
            

    - name: "Fetch tag/branch history"
      shell: bash
      run: |
            export MACOSX_DEPLOYMENT_TARGET=10.9
            git fetch --prune --unshallow
            

    - name: "Install Rust"
      uses: actions-rs/toolchain@v1
      with:
         profile: "minimal"
         toolchain: "stable"
         override: true
         components: "rustfmt"
    - name: "Cache cargo"
      uses: actions/cache@v2
      with:
         path: |
            ~/.cargo/registry
            ~/.cargo/git
            target

         key: "macos-None-2-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}-cargo"
    - name: "Install System Deps"
      shell: bash
      run: |
            export MACOSX_DEPLOYMENT_TARGET=10.9
            ./get-deps
            

    - name: "Build (Release mode)"
      shell: bash
      run: |
            export MACOSX_DEPLOYMENT_TARGET=10.9
            cargo build --all --release
            

    - name: "Test (Release mode)"
      shell: bash
      run: |
            export MACOSX_DEPLOYMENT_TARGET=10.9
            cargo test --all --release
            

    - name: "Package"
      shell: bash
      run: |
            export MACOSX_DEPLOYMENT_TARGET=10.9
            bash ci/deploy.sh
            

    - name: "Upload to Tagged Release"
      uses: softprops/action-gh-release@v1
      with:
         files: "WezTerm-*.zip"
      env:
         GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - name: "Checkout homebrew tap"
      uses: actions/checkout@v2
      with:
         repository: "wez/homebrew-wezterm"
         path: "homebrew-wezterm"
         token: "${{ secrets.GH_PAT }}"
    - name: "Update homebrew tap formula"
      shell: bash
      run: |
            export MACOSX_DEPLOYMENT_TARGET=10.9
            cp wezterm.rb homebrew-wezterm/Formula/wezterm.rb
            

    - name: "Commit homebrew tap changes"
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
         commit_message: "Automated update to match latest tag"
         repository: "homebrew-wezterm"
