name: debian11_continuous

on:
  schedule:
    - cron: "10 3 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - ".cirrus.yml"
      - "docs/**"
      - "ci/build-docs.sh"
      - "ci/generate-docs.py"
      - "ci/subst-release-info.py"
      - ".github/workflows/pages.yml"
      - ".github/ISSUE_TEMPLATE/*"
      - "**/*.md"

jobs:
  build:
    runs-on: "ubuntu-latest"
    container: "debian:11"
    steps:
      - name: "set APT to non-interactive"
        shell: bash
        run: |
          export BUILD_REASON=Schedule
          echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
      - name: "Update APT"
        shell: bash
        run: |
          export BUILD_REASON=Schedule
          apt update
      - name: "Install git"
        shell: bash
        run: |
          export BUILD_REASON=Schedule
          apt-get install -y git
      - name: "Install curl"
        shell: bash
        run: |
          export BUILD_REASON=Schedule
          apt-get install -y curl
      - name: "Update APT"
        shell: bash
        run: |
          export BUILD_REASON=Schedule
          apt update
      - name: "Install https support for apt"
        shell: bash
        run: |
          export BUILD_REASON=Schedule
          apt-get install -y apt-transport-https ca-certificates
      - name: "Install GitHub keyring"
        shell: bash
        run: |
          export BUILD_REASON=Schedule
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
      - name: "Add GitHub package list"
        shell: bash
        run: |
          export BUILD_REASON=Schedule
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
      - name: "Show GitHub package list"
        shell: bash
        run: |
          export BUILD_REASON=Schedule
          cat /etc/apt/sources.list.d/*
      - name: "Update APT again"
        shell: bash
        run: |
          export BUILD_REASON=Schedule
          apt update
      - name: "Install GH CLI"
        shell: bash
        run: |
          export BUILD_REASON=Schedule
          apt install -y gh
      - name: "Ensure /run/sshd exists"
        shell: bash
        run: |
          export BUILD_REASON=Schedule
          mkdir -p /run/sshd
      - name: "Install openssh-server"
        shell: bash
        run: |
          export BUILD_REASON=Schedule
          apt-get install -y openssh-server
      - name: "checkout repo"
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: "Fetch tags"
        shell: bash
        run: |
          export BUILD_REASON=Schedule
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: "Fetch tag/branch history"
        shell: bash
        run: |
          export BUILD_REASON=Schedule
          git fetch --prune --unshallow
      - name: "Install Rust"
        uses: actions-rs/toolchain@v1
        with:
          profile: "minimal"
          toolchain: "stable"
          override: true
          components: "rustfmt"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
      - name: "Cache cargo"
        uses: actions/cache@v2.1.7
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: "debian11-None-2-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}-cargo"
      - name: "Install System Deps"
        shell: bash
        run: |
          export BUILD_REASON=Schedule
          env PATH=$PATH ./get-deps
      - name: "Build (Release mode)"
        shell: bash
        run: |
          export BUILD_REASON=Schedule
          cargo build --all --release
      - name: "Test (Release mode)"
        shell: bash
        run: |
          export BUILD_REASON=Schedule
          cargo test --all --release
      - name: "Package"
        shell: bash
        run: |
          export BUILD_REASON=Schedule
          bash ci/deploy.sh
      - name: "Upload artifact"
        uses: actions/upload-artifact@v2
        with:
          name: "debian11"
          path: |
            wezterm-*.deb
            wezterm-*.xz
          retention-days: 5

  upload:
    runs-on: ubuntu-latest
    steps:
      - name: "Download artifact"
        uses: actions/download-artifact@v2
        with:
          name: "debian11"
      - name: "Upload to Nightly Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: "bash ci/retry.sh gh release upload --clobber nightly wezterm-*.deb wezterm-*.xz"
