name: tag_win

on:
  push:
    tags:
      - "20*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [vs2017-win2016]
        rust_toolchain: [stable-x86_64]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Install Rust
      shell: cmd
      run: |
          curl -sSf -o rustup-init.exe https://win.rustup.rs
          rustup-init.exe -yv --default-toolchain ${{ matrix.rust_toolchain }}
          rustup update ${{ matrix.rust_toolchain }}
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ matrix.os }}-${{ matrix.rust_toolchain }}-cargo-registry-${{ hashFiles('Cargo.lock') }}
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ matrix.os }}-${{ matrix.rust_toolchain }}-cargo-index-${{ hashFiles('Cargo.lock') }}
    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ matrix.os }}-${{ matrix.rust_toolchain }}-cargo-build-target-${{ hashFiles('Cargo.lock') }}
    - name: Package
      shell: cmd
      run: |
        set path "%USERPROFILE%\.cargo\bin;%PATH"
        cargo build --release --all
        bash ci/deploy.sh
    - name: Upload Assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          wezterm-*.rpm
          wezterm-*.deb
          WezTerm-*.zip
          wezterm-*.xz
          weztern-*.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

