[package]
name = "lfucache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { path = "../config" }
fnv = "1.0"
metrics = { version="0.17", features=["std"]}
